
name: "water_bulk_MACE_dipole_pol"
train_file: "data/water_bulk_train.xyz"
test_file: "data/water_bulk_test.xyz"
model: "AtomicDielectricMACE"
model_dir: "MACE_models"
log_dir: "MACE_models"
checkpoints_dir: "MACE_models"
results_dir: "MACE_models"
E0s: "average"
num_channels: 32
max_L: 2
r_max: 5.0
loss: "dipole"
dipole_weight: 1.0
polarizability_weight: 1.0
dipole_key: "REF_dipole" 
polarizability_key: "REF_polarizability"
weight_decay: 5e-10
clip_grad: 1.0
batch_size: 16
valid_batch_size: 16
max_num_epochs: 50
# scheduler_patience: 20
# patience: 50
eval_interval: 1
ema: 'True'
error_table: 'DipoleRMSE'
default_dtype: "float64"
device: cuda
distributed: 'True'
seed: 123
restart_latest: 'True'
save_cpu: 'True'
swa: 'False'
compute_polarizability: 'True'
